### ISSUE TITLE
Incorrect String convertion on class HealthServlet

### ISSUE THREAD

**Issue by fhattori** [ksclarke/freelib-djatoka#67]
In class `info.freelibrary.djatoka.util.HealthServlet` (line 42), the variable `memUsage` receives an incorrect string when using my current locale (pt_BR). For example, instead of returning "0.16", it returns "0,16", thus leading to an exception being raised on line 48, as Java cannot parse that string as a `double`.

```java
        Runtime runtime = Runtime.getRuntime();
        long freeMemory = runtime.freeMemory();
        long totalMemory = runtime.totalMemory();
        long usedMemory = totalMemory - freeMemory;
        double percentage = (double) usedMemory / totalMemory;
        String memUsage = String.format("%.2g", percentage);
        int memory;

        serializer.setIndent(2);
        root.appendChild(health);

        memory = (int) (Double.parseDouble(memUsage) * 100);
```

My OS and Java versions are:
- Java JDK version "1.8.0_73"
- Ubuntu 15.10 (language pt_BR)

**Comment by ksclarke** [comment]
Thanks for reporting this @fhattori. I've checked into the master branch what I think is a fix for this. Would you like to try it out to confirm?

**Comment by fhattori** [comment]
Thanks for answering. I tried the new code and it worked.
